package com.my.digi.visionkids;

import android.content.Context;
import android.os.Bundle;

import java.util.Arrays;

/**
 * Created by Darryl on 12/17/2016.
 */

public class Database {

    String[] exclusionArray, exclusionMidArray;
    Context ourContext;

    public Database(Context c) {
        this.ourContext = c;

        //Dog reference tables
        exclusionArray = new String[]
                {
                        "aquatic plant",
                        "art",
                        "automobile make",
                        "automotive design",
                        "automotive exterior",
                        "banana family",
                        "big cats",
                        "biology",
                        "bird",
                        "bird of prey",
                        "black",
                        "blue",
                        "brand",
                        "brown",
                        "bumper",
                        "camel like mammal",
                        "carnivoran",
                        "cat like mammal",
                        "cattle like mammal",
                        "ceramic",
                        "city car",
                        "close up",
                        "computer component",
                        "crane like bird",
                        "crow like bird",
                        "cut flowers",
                        "design",
                        "display device",
                        "document",
                        "dog breed",
                        "dog breed group",
                        "dog like mammal",
                        "domestic rabbit",
                        "ducks geese and swans",
                        "electronic device",
                        "electronics",
                        "elephants and mammoths",
                        "fashion accessory",
                        "fauna",
                        "flightless bird",
                        "floor",
                        "flooring",
                        "flora",
                        "floristry",
                        "flower",
                        "flower arranging",
                        "flowering plant",
                        "food",
                        "fruit",
                        "furniture",
                        "gadget",
                        "garden roses",
                        "grass family",
                        "green",
                        "hardwood",
                        "horse like mammal",
                        "human body",
                        "illustration",
                        "image",
                        "interior design",
                        "invertebrate",
                        "land plant",
                        "land vehicle",
                        "light",
                        "lighting",
                        "line",
                        "macro photography",
                        "mammal",
                        "material",
                        "morning",
                        "multimedia",
                        "musical instrument",
                        "official",
                        "organism",
                        "pattern",
                        "perching bird",
                        "personal computer hardware",
                        "petal",
                        "pig like mammal",
                        "pink",
                        "plant",
                        "player piano",
                        "plucked string instruments",
                        "plumbing fixture",
                        "presentation",
                        "produce",
                        "product",
                        "profession",
                        "professional",
                        "rabits and hares",
                        "red",
                        "reflection",
                        "reptile",
                        "room",
                        "screenshot",
                        "shape",
                        "small to medium sized cats",
                        "speech",
                        "still life",
                        "strawberries",
                        "string instrument",
                        "sunlight",
                        "technology",
                        "text",
                        "tool",
                        "tourism",
                        "tree",
                        "vacation",
                        "vehicle",
                        "vertebrate",
                        "watercolor paint",
                        "waterway",
                        "weather",
                        "wheel",
                        "white",
                        "wildlife",
                        "wood stain",
                        "yellow"
                };

        exclusionMidArray = new String[]
                {
                        "/m/013sbk",
                        "/m/0jjw",
                        "/m/02ht342",
                        "/m/068mqj",
                        "/m/0h8ls87",
                        "/m/013xk6",
                        "/m/0cdnk",
                        "/m/01540",
                        "/m/015p6",
                        "/m/0f6x8",
                        "/m/019sc",
                        "/m/01g5v",
                        "/m/01cd9",
                        "/m/09q2t",
                        "/m/02mnkq",
                        "/m/01v4x4",
                        "/m/01lrl",
                        "/m/0307l",
                        "/m/0jzz1",
                        "/m/01x5q",
                        "/m/0369ss",
                        "/m/02cqfm",
                        "/m/0h8lprf",
                        "/m/01c4kr",
                        "/m/015lbc",
                        "/m/0ds61d1",
                        "/m/02cwm",
                        "/m/029zz6",
                        "/m/015bv3",
                        "/m/0kpmf",
                        "/m/02xl47d",
                        "/m/01z5f",
                        "/m/06bs13",
                        "/m/01c_0l",
                        "/m/0bs7_0t",
                        "/m/02mrp",
                        "/m/07kbbhf",
                        "/m/0463sg",
                        "/m/035qhg",
                        "/m/03qqnt",
                        "/m/0l7_8",
                        "/m/01c34b",
                        "/m/03bmqb",
                        "/m/02hcw1",
                        "/m/0c9ph5",
                        "/m/0ggjrhd",
                        "/m/04sjm",
                        "/m/02wbm",
                        "/m/02xwb",
                        "/m/0c_jw",
                        "/m/02mf1n",
                        "/m/0fpjlj9",
                        "/m/0fkrk",
                        "/m/038hg",
                        "/m/020g49",
                        "/m/02s3y",
                        "/m/02p0tk3",
                        "/m/01kr8f",
                        "/m/0jg24",
                        "/m/02rfdq",
                        "/m/03xxp",
                        "/m/01v728",
                        "/m/01prls",
                        "/m/04k84",
                        "/m/019sc6",
                        "/m/03scnj",
                        "/m/03rbf6",
                        "/m/04rky",
                        "/m/01l0y0",
                        "/m/02_ktj",
                        "/m/0541p",
                        "/m/04szw",
                        "/m/035y33",
                        "/m/05nnm",
                        "/m/0hwky",
                        "/m/0cjvf",
                        "/m/0j24d_1",
                        "/m/016q19",
                        "/m/020bgr",
                        "/m/01fklc",
                        "/m/05s2s",
                        "/m/012lk9",
                        "/m/0fx80y",
                        "/m/02pkr5",
                        "/m/02y3rj",
                        "/m/036qh8",
                        "/m/01jwgf",
                        "/m/063km",
                        "/m/01qkbx",
                        "/m/019dxh",
                        "/m/06fvc",
                        "/m/021215",
                        "/m/06bt6",
                        "/m/06ht1",
                        "/m/01zbnw",
                        "/m/016nqd",
                        "/m/07k6w8",
                        "/m/09x0r",
                        "/m/01spzs",
                        "/m/0fbdb",
                        "/m/011_f4",
                        "/m/06z0n",
                        "/m/07c1v",
                        "/m/07s6nbt",
                        "/m/07k1x",
                        "/m/07bxq",
                        "/m/07j7r",
                        "/m/02jwqh",
                        "/m/07yv9",
                        "/m/09686",
                        "/m/018ktp",
                        "/m/017m8l",
                        "/m/0866r",
                        "/m/083wq",
                        "/m/083jv",
                        "/m/01280g",
                        "/m/05t06b",
                        "/m/088fh"
                };
    }

    public boolean foundExclusion (String mid){
        if (Arrays.asList(exclusionMidArray).contains(mid))
            return true;
        else
            return false;
    }

    public int getLength (){
        return exclusionArray.length;
    }
}